---
- name: Intro Ansible
  hosts: VMAzure
  remote_user: maxime
  become: yes
  become_method: sudo

  tasks:
    - name: Installation de git
      apt: 
        name: git 
        update_cache: yes
        state: latest

    - name: installation de postgres
      apt: 
        name: postgresql
        update_cache: yes
        state: latest
    
    - name: installation de pip
      apt:
        name: python-pip
        state: latest

    - name: installation de pip3
      apt:
        name: python3-pip
        state: latest

    - name: Installation des packages python sur pip2
      pip:
        name: 
          - psycopg2-binary
          - Flask

    - name: Installation des packages python sur pip3
      pip:
        name: 
          - psycopg2-binary
          - Flask
        executable: pip3
    
    - name: pd reset database user
      become: yes
      become_method: sudo
      become_user: postgres
      postgresql_user: 
        db: postgres
        name: postgres
        password: "123" 

    - name: Clone a repo git
      git:
        repo: https://github.com/LuffyStar93/flask-ansible.git
        dest: /home/maxime/app